apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-ingress
  annotations: 
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/proxy-body-size: 100m
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend-service
                port:
                  number: 80
          - path: /api/add
            pathType: Prefix
            backend:
              service:
                name: backendadd-service
                port:
                  number: 80
          - path: /api/bid
            pathType: Prefix
            backend:
              service:
                name: backendbid-service
                port:
                  number: 80
          - path: /api/search
            pathType: Prefix
            backend:
              service:
                name: backendsearch-service
                port:
                  number: 80
          - path: /api/image
            pathType: Prefix
            backend:
              service:
                name: backendimage-service
                port:
                  number: 80
          - path: /api/auth
            pathType: Prefix
            backend:
              service:
                name: backendauth-service
                port:
                  number: 80
          - path: /api/message
            pathType: Prefix
            backend:
              service:
                name: backendmessage-service
                port:
                  number: 80
          - path: /api/notification
            pathType: Prefix
            backend:
              service:
                name: backendnotification-service
                port:
                  number: 80
          