apiVersion: v1
kind: Service
metadata:
  name: kwetter-frontend-service
spec:
  selector:
    app: kwetter-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: userprofileapi-service
spec:
  selector:
    app: userprofileapi
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: tweetapi-service
spec:
  selector:
    app: tweetapi
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80